In [1]:
import cv2
from PIL import Image
import numpy as np
import matplotlib.image as Image
#img=Image.open('D:\Image processing\wolf.jpg')
img=cv2.imread('D:\Image processing\wolf.jpg')

In [2]:
cv2.imshow('image',img)
#cv2.waitKey(0)

In [3]:
"""width=img.width
height=img.height"""

'width=img.width\nheight=img.height'

In [4]:
"""print("The height of the image is: ", height)
print("The width of the image is: ", width)"""

'print("The height of the image is: ", height)\nprint("The width of the image is: ", width)'

In [11]:
import cv2
from PIL import Image
import numpy as np
import matplotlib.image as image
img=cv2.imread("wolf.jpg",0)
print("no of channels is:"+str(img.ndim))
print("no of channels is:",img.shape)
cv2.imshow('images',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

no of channels is:2
no of channels is: (183, 275)


In [14]:
import cv2
filepath='wolf.jpg'
img=Image.open(filepath)
new=img.resize((75,75))
img.show()
new.show()

In [15]:
pic=cv2.imread('wolf.jpg')
print('the shape of the image is',pic.shape)
print('the image as array is')
print(pic)

the shape of the image is (183, 275, 3)
the image as array is
[[[35 61 75]
  [35 61 75]
  [36 62 76]
  ...
  [40 71 72]
  [38 72 72]
  [38 72 72]]

 [[36 62 76]
  [36 62 76]
  [37 63 77]
  ...
  [39 70 71]
  [37 71 71]
  [37 71 71]]

 [[38 64 78]
  [38 64 78]
  [39 65 79]
  ...
  [39 70 71]
  [37 71 71]
  [37 71 71]]

 ...

 [[45 96 92]
  [45 96 92]
  [45 97 90]
  ...
  [30 88 77]
  [30 88 77]
  [30 88 77]]

 [[46 97 93]
  [46 97 93]
  [45 97 90]
  ...
  [32 90 79]
  [32 90 79]
  [32 90 79]]

 [[47 98 94]
  [46 97 93]
  [46 98 91]
  ...
  [33 91 80]
  [33 91 80]
  [33 91 80]]]


In [22]:
import cv2
img=cv2.imread("wolf.jpg",)
ret,bw_img=cv2.threshold(img,225,127,cv2.THRESH_BINARY)
cv2.imshow("Binary",bw_img)
cv2.waitKey(0)
cv2.destroyAllWindows()